(defun c:LoadMyVBAs()
  (vl-vbaload "F:/Gaurav/civil3D/DrawEquation.dvb")
  (vl-vbaload "F:/Gaurav/civil3D/Area_multiple.dvb")
  )
(defun c:SlimLayers()
  (vl-vbarun "SlimLayers")
  )
(defun c:DrawEquation()
  (vl-vbarun "drawEquation")
  )
(defun c:scaleLine()
  (vl-vbarun "scaleLine")
  )

(defun c:pclose()
  (vl-vbarun "pclose")	
)

(defun c:NewElevation()
  (vl-vbarun "Elevation")	
)

(defun c:ExElevation()
  (vl-vbarun "Elevation_ExistingBlock")
  )

(defun c:HatchAll()
  (vl-vbarun "HatchAll")
  )
(defun c:Cross()
  (vl-vbarun "cross")
  )
(defun c:RED()
  (vl-vbarun "Red")
  )
(defun c:OverRideDIM()
  (vl-vbarun "OverRideDIM")
    )
(defun c:SPattern()
  (vl-vbarun "DrawSlopePattern")
    )
(defun c:isclosed()
  (vl-vbarun "isclosed")
    )

(defun c:Hmove()
  (vl-vbarun "Hmove")
    )

(defun c:Vmove()
  (vl-vbarun "Vmove")
    )

(defun c:Zmove()
  (vl-vbarun "Zmove")
    )
